name: clinical_trial_data_pipeline
channels:
  - conda-forge
dependencies:
  - python=3.11.2
  - dbt-core
  - dbt-postgres
  - flask
  - duckdb
  - transformers
  - sentence-transformers
  - pip
  - apache-airflow
  - pandas
  - requests
  - psutil
  - pytest
  - pip:
      - apache-airflow
      - dlt
      - dotenv
