dbt_models:
  outputs:
    dev:
      type: duckdb
      path: "/opt/airflow/src/data/clinical_trial_data.duckdb"
      threads: 1

    prod:
      type: duckdb
      path: "/opt/airflow/src/data/clinical_trial_data.duckdb"
      threads: 4

  target: dev